# Generated by Django 5.1.1 on 2024-09-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='imagenes/establecimientos/banners/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagenes/establecimientos/logos/')),
                ('direccion', models.CharField(max_length=255)),
                ('coordenada_x', models.DecimalField(decimal_places=8, max_digits=10)),
                ('coordenada_y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('rango_de_precios', models.CharField(blank=True, max_length=5)),
                ('nro_ref', models.CharField(blank=True, default='', max_length=13)),
                ('em_ref', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_etiqueta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_etiqueta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroEvento',
            fields=[
                ('id_genero_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_genero', models.CharField(max_length=40)),
                ('descripcion_genero', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30)),
                ('descripcion_tipo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('p_field', models.CharField(blank=True, max_length=50, null=True)),
                ('g_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_consumo', models.CharField(max_length=20)),
                ('precio_consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_consumo', models.CharField(blank=True, max_length=100)),
                ('id_establecimiento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
                ('id_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='imagenes/eventos/banners/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagenes/eventos/logos/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
                ('id_genero_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_entrada', models.CharField(max_length=20)),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_entrada', models.CharField(max_length=100)),
                ('id_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoestablecimiento'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento_asistido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionEvento',
            fields=[
                ('id_valoracion_evento', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=50)),
                ('fecha_publicacion', models.DateTimeField()),
                ('id_asistencia_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('id_establecimiento_visitado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionEstablecimiento',
            fields=[
                ('id_valoracion_establecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=50)),
                ('fecha_publicacion', models.DateTimeField()),
                ('id_visita_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visita')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imagen')),
            ],
            options={
                'unique_together': {('evento', 'imagen')},
            },
        ),
        migrations.CreateModel(
            name='GaleriaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imagen')),
            ],
            options={
                'unique_together': {('establecimiento', 'imagen')},
            },
        ),
    ]
